apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ .Release.Name }}
  namespace: {{ .Release.namespace }}
  labels:
    app: ervcp
spec:
  selector:
    matchLabels:
      app: ervcp
  replicas:  {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: ervcp
    spec:
      containers:
      - name: app
        image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: ERVCP_PORT
          value: "{{ .Values.appPort }}"
        - name: ERVCP_DB_HOST
          value: "{{ .Values.simple_redis.redisMaster }}"
        - name: ERVCP_DB_PORT
          value: "{{ .Values.simple_redis.redisPort }}"
        resources:
            {{- toYaml .Values.resources | nindent 12 }}
        ports:
        - containerPort: {{ .Values.appPort }}
