# master configuration
masterImage:
  repository: docker.io
  name: redis
  tag:  5.0

redisMaster: redis-master
redisPort: 6379 

masterReplicaCount: 1
masterResources:
   requests:
    cpu: 100m
    memory: 128Mi
