apiVersion: v1
kind: Service
metadata:
  name:  {{ .Values.workerName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: redis
    role: slave
    tier: backend
spec:
  ports:
  - port: {{ .Values.redisPort }}
  selector:
    app: redis
    role: slave
    tier: backend
