apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name:  {{ .Values.workerName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
      role: slave
      tier: backend
  replicas:  {{ .Values.workerReplicaCount }}
  template:
    metadata:
      labels:
        app: redis
        role: slave
        tier: backend
    spec:
      containers:
      - name: slave
        image: "{{ .Values.workerImage.repository }}/{{ .Values.workerImage.name }}:{{ .Values.workerImage.tag }}"
        imagePullPolicy: IfNotPresent 
        resources:
            {{- toYaml .Values.workerResources | nindent 12 }}
        env:
          # use kube-dns to resolve names and provide connectivity master-worker
          - name: GET_HOSTS_FROM
            value: dns
        ports:
        - containerPort: {{ .Values.redisPort }}
