redisMasterName: redis-master
redisPort: 6379
redisPassword: ''

# redis subchart config
simple_redis:
    redisMaster: redis-master
    redisPort: 6379

# ervcp application
replicaCount: 1

image:
  repository: vnaumov
  name: ervcp
  tag: latest
  pullPolicy: Always

appPort: 8080
service:
  type: LoadBalancer

resources:
   requests:
    cpu: 100m
    memory: 128Mi
